/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

/**
 *
 * @author moises
 */
public class JFramePrecificacao extends javax.swing.JFrame {

    double num1, num2, num3, num4, num5, num6, num7, num8, num9, num10, num11, num12,num13,num20, num21,num22,num23,num14, num24,num25,num15,num26,num27,num16,num28, num29, num30, num31, num32,num33;

    /**
     * Creates new form JFramePrecificacao
     */
    public JFramePrecificacao() {
        initComponents();
        jTextField3PrecoUnitario.grabFocus(); //focar ao iniciar o programa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1PrecoUnitario = new javax.swing.JLabel();
        jLabel2ImpostoFederal = new javax.swing.JLabel();
        jLabel3ImpostoEstadual = new javax.swing.JLabel();
        jLabel4Frete = new javax.swing.JLabel();
        jLabel5CustosGerais = new javax.swing.JLabel();
        jLabel6GanhoLivre = new javax.swing.JLabel();
        jLabel7PrecodeVenda = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3PrecoUnitario = new javax.swing.JTextField();
        jTextField4ImpostoFederal = new javax.swing.JTextField();
        jTextField5ImpostoEstadual = new javax.swing.JTextField();
        jTextField6Frete = new javax.swing.JTextField();
        jTextField7CustosGerais = new javax.swing.JTextField();
        jTextField8GanhoLivre = new javax.swing.JTextField();
        jTextField9RseultadoImpostoFederal = new javax.swing.JTextField();
        jTextField10ResultadoFrete = new javax.swing.JTextField();
        jTextField11ResultadoImpostoEstadual = new javax.swing.JTextField();
        jTextField12ResultadoCustosGerais = new javax.swing.JTextField();
        jTextField13ResultadoGanhoLivre = new javax.swing.JTextField();
        jTextField14ResultadoPrecoVenda = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processo de Precificação");

        jLabel1PrecoUnitario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1PrecoUnitario.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1PrecoUnitario.setText("Digite aqui o Preço Unitário do Produto:");

        jLabel2ImpostoFederal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2ImpostoFederal.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2ImpostoFederal.setText("O Imposto Federal sobre o produto Custa:");

        jLabel3ImpostoEstadual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3ImpostoEstadual.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3ImpostoEstadual.setText("O Imposto Estadual sobre o produto Custa:");

        jLabel4Frete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4Frete.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4Frete.setText("O preço do Frete Custa:");

        jLabel5CustosGerais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5CustosGerais.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5CustosGerais.setText("Os Custos Gerais são de:");

        jLabel6GanhoLivre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6GanhoLivre.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6GanhoLivre.setText("O Ganho Livre obtido com a venda do produto será de:");

        jLabel7PrecodeVenda.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7PrecodeVenda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7PrecodeVenda.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7PrecodeVenda.setText("O Preço de Venda é de: ");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 153));
        jTextField1.setText("               Programa de Processo de Precificação");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Digite o percentual do Imposto federal sobre o produto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Digite o percentual do Imposto Estadual sobre o produto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Digite o percentual do Frete sobre o produto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Digite o percentual dos Custos Gerais sobre o produto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Digite o ganho livre sobre o produto:");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextField2.setText("                                 Resultados");

        jTextField3PrecoUnitario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3PrecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3PrecoUnitarioActionPerformed(evt);
            }
        });

        jTextField4ImpostoFederal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4ImpostoFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ImpostoFederalActionPerformed(evt);
            }
        });

        jTextField5ImpostoEstadual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5ImpostoEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ImpostoEstadualActionPerformed(evt);
            }
        });

        jTextField6Frete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6Frete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6FreteActionPerformed(evt);
            }
        });

        jTextField7CustosGerais.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7CustosGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7CustosGeraisActionPerformed(evt);
            }
        });

        jTextField8GanhoLivre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8GanhoLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8GanhoLivreActionPerformed(evt);
            }
        });

        jTextField9RseultadoImpostoFederal.setEditable(false);
        jTextField9RseultadoImpostoFederal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9RseultadoImpostoFederal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9RseultadoImpostoFederalActionPerformed(evt);
            }
        });

        jTextField10ResultadoFrete.setEditable(false);
        jTextField10ResultadoFrete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10ResultadoFrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ResultadoFreteActionPerformed(evt);
            }
        });

        jTextField11ResultadoImpostoEstadual.setEditable(false);
        jTextField11ResultadoImpostoEstadual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11ResultadoImpostoEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ResultadoImpostoEstadualActionPerformed(evt);
            }
        });

        jTextField12ResultadoCustosGerais.setEditable(false);
        jTextField12ResultadoCustosGerais.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12ResultadoCustosGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ResultadoCustosGeraisActionPerformed(evt);
            }
        });

        jTextField13ResultadoGanhoLivre.setEditable(false);
        jTextField13ResultadoGanhoLivre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13ResultadoGanhoLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ResultadoGanhoLivreActionPerformed(evt);
            }
        });

        jTextField14ResultadoPrecoVenda.setEditable(false);
        jTextField14ResultadoPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField14ResultadoPrecoVenda.setForeground(new java.awt.Color(255, 0, 0));
        jTextField14ResultadoPrecoVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14ResultadoPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ResultadoPrecoVendaActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2ImpostoFederal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9RseultadoImpostoFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4Frete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField10ResultadoFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3ImpostoEstadual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11ResultadoImpostoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5CustosGerais)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField12ResultadoCustosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(1, 1, 1)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8GanhoLivre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField7CustosGerais, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField6Frete)
                                    .addComponent(jTextField4ImpostoFederal)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1PrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3PrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5ImpostoEstadual))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6GanhoLivre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField13ResultadoGanhoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7PrecodeVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14ResultadoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1PrecoUnitario)
                    .addComponent(jTextField3PrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField4ImpostoFederal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5ImpostoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6Frete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField7CustosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField8GanhoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2ImpostoFederal)
                    .addComponent(jLabel4Frete)
                    .addComponent(jTextField9RseultadoImpostoFederal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10ResultadoFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3ImpostoEstadual)
                    .addComponent(jLabel5CustosGerais)
                    .addComponent(jTextField11ResultadoImpostoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12ResultadoCustosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6GanhoLivre)
                    .addComponent(jTextField13ResultadoGanhoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7PrecodeVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jTextField14ResultadoPrecoVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3PrecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3PrecoUnitarioActionPerformed
       
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        jTextField3PrecoUnitario.setText(String.valueOf(num1));
        
         jTextField14ResultadoPrecoVenda.setText(String.valueOf(num1));
        jTextField3PrecoUnitario.transferFocus(); //ao apertar enter, vai pro proximo campo
    }//GEN-LAST:event_jTextField3PrecoUnitarioActionPerformed
           
            
    private void jTextField4ImpostoFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ImpostoFederalActionPerformed
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        num2 = Double.parseDouble(jTextField4ImpostoFederal.getText());
        
        jTextField4ImpostoFederal.setText(String.valueOf(num2));

        num7 = ((num2/100) * num1);
        jTextField9RseultadoImpostoFederal.setText(String.valueOf(num7));
        // We have to parse the text to a type Double.
        
        jTextField14ResultadoPrecoVenda.setText("");        

        num12 = (num1 + num7);
        jTextField14ResultadoPrecoVenda.setText(String.valueOf(num12));
        jTextField4ImpostoFederal.transferFocus(); //apertando enter, transfere foco p/proximo campo
    }//GEN-LAST:event_jTextField4ImpostoFederalActionPerformed
        
    private void jTextField5ImpostoEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ImpostoEstadualActionPerformed
         
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        num2 = Double.parseDouble(jTextField4ImpostoFederal.getText());
        num3 = Double.parseDouble(jTextField5ImpostoEstadual.getText());
        
        jTextField5ImpostoEstadual.setText(String.valueOf(num3));        
        
        num20 = ((num2/100) * num1);
        num21 = (num1 + num20);
        
                
        num8 = (num1 * (num3/100));
       
        jTextField11ResultadoImpostoEstadual.setText(String.valueOf(num8));         
                        
        jTextField14ResultadoPrecoVenda.setText("");  
        
        num13 = (num21 + num8);
        jTextField14ResultadoPrecoVenda.setText(String.valueOf(num13));
        jTextField5ImpostoEstadual.transferFocus();
    }//GEN-LAST:event_jTextField5ImpostoEstadualActionPerformed

    private void jTextField6FreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6FreteActionPerformed
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        num2 = Double.parseDouble(jTextField4ImpostoFederal.getText());
        num3 = Double.parseDouble(jTextField5ImpostoEstadual.getText());
        num4 = Double.parseDouble(jTextField6Frete.getText());
        
        jTextField6Frete.setText(String.valueOf(num4));
        
        
        num28 = (num1 * (num2/100));
         num22 = (num1 * (num3/100));
         num23 = (num1 + num22+ num28);
         
        num9 = (num1 * (num4/100));
        
        jTextField10ResultadoFrete.setText(String.valueOf(num9));
        
         jTextField14ResultadoPrecoVenda.setText(""); 
        
        
        num14 = (num23 + num9);
        jTextField14ResultadoPrecoVenda.setText(String.valueOf(num14));
        jTextField6Frete.transferFocus();
    }//GEN-LAST:event_jTextField6FreteActionPerformed

    private void jTextField7CustosGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7CustosGeraisActionPerformed
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        num2 = Double.parseDouble(jTextField4ImpostoFederal.getText());
        num3 = Double.parseDouble(jTextField5ImpostoEstadual.getText());
        num4 = Double.parseDouble(jTextField6Frete.getText());
        num5 = Double.parseDouble(jTextField7CustosGerais.getText());
        
        jTextField7CustosGerais.setText(String.valueOf(num5));
        
        num29 = (num1 * (num2/100));
        num30 = (num1 * (num3/100));
        num24 = (num1 * (num4/100));
         num25 = (num29 + num1 + num24 + num30);

        num10 = (num1 * (num5/100));
        
        jTextField12ResultadoCustosGerais.setText(String.valueOf(num10));
        
                 jTextField14ResultadoPrecoVenda.setText(""); 

        num15 = (num25 + num10);
        jTextField14ResultadoPrecoVenda.setText(String.valueOf(num15));
        jTextField7CustosGerais.transferFocus();
    }//GEN-LAST:event_jTextField7CustosGeraisActionPerformed

    private void jTextField8GanhoLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8GanhoLivreActionPerformed
        num1 = Double.parseDouble(jTextField3PrecoUnitario.getText());
        num2 = Double.parseDouble(jTextField4ImpostoFederal.getText());
        num3 = Double.parseDouble(jTextField5ImpostoEstadual.getText());
        num4 = Double.parseDouble(jTextField6Frete.getText());
        num5 = Double.parseDouble(jTextField7CustosGerais.getText());
        num6 = Double.parseDouble(jTextField8GanhoLivre.getText());
       
        jTextField8GanhoLivre.setText(String.valueOf(num6));
        
        
        num31 = (num1 * (num2/100));
        num32 = (num1 * (num3/100));
        num33 = (num1 * (num4/100));
         num26 = (num1 * (num5/100));
         num27 = (num1 + num26 + num31 + num32 + num33);

        num11 = (num1 * (num6/100));
        
        jTextField13ResultadoGanhoLivre.setText(String.valueOf(num11));
        
           jTextField14ResultadoPrecoVenda.setText(""); 

        num16 = (num27 + num11);
        jTextField14ResultadoPrecoVenda.setText(String.valueOf(num16));
        jTextField8GanhoLivre.transferFocus();
    }//GEN-LAST:event_jTextField8GanhoLivreActionPerformed

    private void jTextField9RseultadoImpostoFederalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9RseultadoImpostoFederalActionPerformed


    }//GEN-LAST:event_jTextField9RseultadoImpostoFederalActionPerformed

    private void jTextField10ResultadoFreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ResultadoFreteActionPerformed

    }//GEN-LAST:event_jTextField10ResultadoFreteActionPerformed

    private void jTextField11ResultadoImpostoEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ResultadoImpostoEstadualActionPerformed

    }//GEN-LAST:event_jTextField11ResultadoImpostoEstadualActionPerformed

    private void jTextField12ResultadoCustosGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ResultadoCustosGeraisActionPerformed

    }//GEN-LAST:event_jTextField12ResultadoCustosGeraisActionPerformed

    private void jTextField13ResultadoGanhoLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ResultadoGanhoLivreActionPerformed

    }//GEN-LAST:event_jTextField13ResultadoGanhoLivreActionPerformed

    private void jTextField14ResultadoPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ResultadoPrecoVendaActionPerformed
       
    }//GEN-LAST:event_jTextField14ResultadoPrecoVendaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField3PrecoUnitario.setText("");
        jTextField4ImpostoFederal.setText("");
        jTextField5ImpostoEstadual.setText("");
        jTextField6Frete.setText("");
        jTextField7CustosGerais.setText("");
        jTextField8GanhoLivre.setText("");
        jTextField9RseultadoImpostoFederal.setText("");
        jTextField10ResultadoFrete.setText("");
        jTextField11ResultadoImpostoEstadual.setText("");
        jTextField12ResultadoCustosGerais.setText("");
        jTextField13ResultadoGanhoLivre.setText("");
        jTextField14ResultadoPrecoVenda.setText(""); //limpa o resultado

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrecificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrecificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1PrecoUnitario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2ImpostoFederal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3ImpostoEstadual;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Frete;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5CustosGerais;
    private javax.swing.JLabel jLabel6GanhoLivre;
    private javax.swing.JLabel jLabel7PrecodeVenda;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10ResultadoFrete;
    private javax.swing.JTextField jTextField11ResultadoImpostoEstadual;
    private javax.swing.JTextField jTextField12ResultadoCustosGerais;
    private javax.swing.JTextField jTextField13ResultadoGanhoLivre;
    private javax.swing.JTextField jTextField14ResultadoPrecoVenda;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3PrecoUnitario;
    private javax.swing.JTextField jTextField4ImpostoFederal;
    private javax.swing.JTextField jTextField5ImpostoEstadual;
    private javax.swing.JTextField jTextField6Frete;
    private javax.swing.JTextField jTextField7CustosGerais;
    private javax.swing.JTextField jTextField8GanhoLivre;
    private javax.swing.JTextField jTextField9RseultadoImpostoFederal;
    // End of variables declaration//GEN-END:variables
}
